import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeGender, cleanTranslation, toLessonWord } from './lib/vocab-normalize.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCE = join(ROOT, 'data-source', 'enriched_vocab_full.json');
const ID_OFFSET = 100000; // keep generated ids clear of curated ids (1-28)

const raw = JSON.parse(readFileSync(SOURCE, 'utf-8'));
if (!Array.isArray(raw)) throw new Error('Expected source JSON to be an array');

const lessonWords = [];
const seenIds = new Set();
let nonNoun = 0;
let excludedNoGender = 0;
let excludedNoTranslation = 0;

for (const entry of raw) {
  if (!entry.grammar_noun) { nonNoun++; continue; }
  const id = ID_OFFSET + entry.rank;
  const lw = toLessonWord(entry, id);
  if (!lw) {
    if (!normalizeGender(entry)) excludedNoGender++;
    else if (!cleanTranslation(entry)) excludedNoTranslation++;
    continue;
  }
  if (seenIds.has(lw.id)) throw new Error(`Duplicate generated id ${lw.id} (${lw.german})`);
  if (lw.id <= 28) throw new Error(`Generated id ${lw.id} collides with curated range (1-28)`);
  seenIds.add(lw.id);
  lessonWords.push(lw);
}

lessonWords.sort((a, b) => a.rank - b.rank);
if (lessonWords.length === 0) throw new Error('No usable lesson words produced — aborting');

// Artifact 1: full dictionary (lazy-loaded from public/).
mkdirSync(join(ROOT, 'public', 'vocab'), { recursive: true });
writeFileSync(join(ROOT, 'public', 'vocab', 'dictionary.json'), JSON.stringify(raw));

// Artifact 2: bundled, type-checked lesson words.
mkdirSync(join(ROOT, 'src', 'data', 'generated'), { recursive: true });
const ts =
  `// AUTO-GENERATED by scripts/build-vocab.mjs — do not edit by hand.\n` +
  `import type { LessonWord } from '../vocab-types';\n\n` +
  `export const lessonWords: LessonWord[] = ${JSON.stringify(lessonWords)};\n`;
writeFileSync(join(ROOT, 'src', 'data', 'generated', 'lessonWords.ts'), ts);

console.log('--- build-vocab report ---');
console.log(`Total source entries:        ${raw.length}`);
console.log(`Non-noun (skipped):          ${nonNoun}`);
console.log(`Excluded — no valid gender:  ${excludedNoGender}`);
console.log(`Excluded — no translation:   ${excludedNoTranslation}`);
console.log(`Usable lesson words:         ${lessonWords.length}`);
console.log(`dictionary.json:             public/vocab/dictionary.json`);
console.log(`lessonWords.ts:              src/data/generated/lessonWords.ts`);
